# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 473ec2f8447604145892ff8c008bc6b9637b550dcd2aa6224ac2ea05b126c3d554a5eb4983490f6f64de8c95c27d63ad0604d68ac10c938b3a525d5d42e6a823

test:
  secret_key_base: 550580b2d9edf8a45d0763f8846286cbeabe4c05962b24e0942c3fedaae90fcc534aa782ce187b2d6e997fc33064516ea50aeef4ad8f4de97f2755483ea4d4b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
